module.exports = {
  DB: process.env.DB || '',
  PORT: process.env.PORT || '',
  IS_CONSOLE_LOG: process.env.IS_CONSOLE_LOG || '',
  CLIENT_ID: process.env.CLIENT_ID ||  "",
  CLIENT_SECRET : process.env.CLEINT_SECRET || "",
  CLIENT_TWILIO_SID: process.env.CLIENT_TWILIO_SID  || "",
  CLIENT_TWILIO_API_KEY: process.env.CLIENT_TWILIO_API_KEY  || "",
  CLIENT_TWILIO_SECRET: process.env.CLIENT_TWILIO_SECRET  || "",
  CLIENT_SERVICE_SID: process.env.CLIENT_SERVICE_SID  || "",
  CLIENT_IDENTITY: process.env.CLIENT_IDENTITY  || "",
  STRIPE_PRIVATE_KEY: process.env.STRIPE_PRIVATE_KEY || "",
  STRIPE_CLIENT_ID: process.env.STRIPE_CLIENT_ID || "",
  AMQP_HOST_URL: process.env.AMQP_HOST_URL || "",
  NOTIFICATION_EXCHANGE: process.env.NOTIFICATION_EXCHANGE || "",
  USER_EXCHANGE: process.env.USER_EXCHANGE || "",
  USER_SERVICE_QUEUE: process.env.USER_SERVICE_QUEUE || "",
  AUTH0_MGMG_BASEURL: process.env.AUTH0_MGMG_BASEURL || "",
  SENDER_EMAIL: process.env.SENDER_EMAIL || '',
  ADMIN_EMAIL: process.env.ADMIN_EMAIL || '',
  AUTH0_AUDIENCE: process.env.AUTH0_AUDIENCE || "",
  STRIPE_PRIVATE_KEY: process.env.STRIPE_PRIVATE_KEY || "",
  STRIPE_CLIENT_ID: process.env.STRIPE_CLIENT_ID || ""
}
